apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-gltk
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-aoeo-tenant/rhtap-demo-app/hacbs-test-project-gltk@sha256:b9c8980d32c5e099865fbab218a20c0abc706350f01abaac49f4823b76663ec2
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
